File "c:\Users\Stuart\Python Scripts\scifiRPG\character_creation_funcs.py", line 165, in generate_faction_characters
    location=location_objects.get,  #NOTE
             ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get'

File "c:\Users\Stuart\Python Scripts\scifiRPG\character_creation_funcs.py", line 165, in generate_faction_characters
    location=location_objects.get,  #NOTE
             ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get'

for _ in range(random.randint(2, 3)):
            characters.append(Manager(name=generate_name(None, random.choice(["Male", "Female"])), faction=faction, region=faction.region or faction.region,  
                location=location_objects.get,  #NOTE
                initial_motivations=["influence"]))

        for _ in range(random.randint(5, 10)):
            characters.append(Employee(name=generate_name(None, random.choice(["Male", "Female"])), faction=faction, region=faction.region or faction.region,  
                location=MunicipalBuilding,  #'NOTE'
                initial_motivations=["influence"]))

At some point there must have been two potential ways of doing things, judgin by the two NOTE comments I left.


